# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

replyByEmail = false

mainSections = ["dsblog", "wiaposts", "pmblog", "samskrutyatra"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/featured.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = false
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "docs"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background



[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = true
  showDateUpdated = false
  showAuthor = false
  # showAuthorBottom = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
  # editAppendPath = true
  # seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 6
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = true
  sharingLinks = [ "linkedin", "twitter", "whatsapp", "telegram", "pinterest", "facebook", "email", "bluesky", "reddit"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = true
  
[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  #projectId = "blowfish-21fff"
  #storageBucket = "blowfish-21fff.appspot.com"
  #messagingSenderId = "60108104191"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  #measurementId = "G-PEDMYR1V0K"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = false

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = false

[buymeacoffee]
  identifier = "harithapliyal"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"

[verification]
  google = "google926354b0a3e2593e.html"
  # bing = ""
  # pinterest = ""
  # yandex = ""

[rssnext]
  # feedId = ""
  # userId = ""


[social]
    # Share buttons to show
    share = ["facebook", "twitter", "linkedin", "reddit", "whatsapp", "email"]
  
  # Social media accounts - used for footer links and share buttons
  [social.links]
    github = "https://github.com/dasarpai"
    twitter = "https://twitter.com/dasarpai"
    linkedin = "https://linkedin.com/in/dasarpai"
    facebook = "https://facebook.com/dasarpai"
    instagram = "https://instagram.com/"
    youtube = "https://youtube.com/dasarpai"
  
  # Social media usernames - used for @mentions and attributions
  [social.usernames]
    github = "dasarpai"
    twitter = "dasarpai"
    linkedin = "harithapliyal"
    facebook = "dasarpai"
    instagram = "dasarpai"
    youtube = "dasarpai"
  
  # Twitter specific settings (for Docsy compatibility)
  [twitter]
    creator = "dasarpai"
    site = "dasarpai"
    username = "dasarpai"  # This fixes your current error

[links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[links.user]]
	name = "Slack"
	url = "https://join.slack.com/t/dasarpai/shared_invite/zt-2mg1j7ddw-0QYA9IAvFFRKw51ZBK6mkQ"
	icon = "fab fa-slack"
  desc = "Chat with other project users in #users"
[[links.user]]
	name = "User mailing list"
	url = "https://groups.google.com/forum/#!forum/agones-discuss"
	icon = "fa fa-envelope"
	desc = "Discussion and help from your fellow users"
[[links.user]]
	name ="Twitter"
	url = "https://twitter.com/dasarpai"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"
[[links.user]]
	name ="Community Meetings"
	url = "https://www.youtube.com/playlist?list=PLhkWKwFGACw2dFpdmwxOyUCzlGP2-n7uF"
	icon = "fab fa-youtube"
	desc = "Live discussion of new features and issues, see the <a href=\"https://github.com/googleforgames/agones/blob/main/CONTRIBUTING.md#community-meetings\">calendar</a> or <a href=\"https://groups.google.com/forum/#!forum/agones-discuss\">mailing list</a> for details"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[links.developer]]
	name = "GitHub"
	url = "https://github.com/dasarpai/dasarpai-agones"
	icon = "fab fa-github"
	desc = "Development takes place here!"
[[links.developer]]
	name = "Slack"
	url = "https://join.slack.com/t/dasarpai/shared_invite/zt-2mg1j7ddw-0QYA9IAvFFRKw51ZBK6mkQ"
	icon = "fab fa-slack"
	desc = "Chat with other project developers in #development"
[[links.developer]]
	name ="Community Meetings"
	url = "https://www.youtube.com/playlist?list=PLhkWKwFGACw2dFpdmwxOyUCzlGP2-n7uF"
	icon = "fab fa-youtube"
	desc = "Live discussion of new features and issues, see the <a href=\"https://github.com/dasarpai/agones/blob/main/CONTRIBUTING.md#community-meetings\">calendar</a> or <a href=\"https://groups.google.com/forum/#!forum/agones-discuss\">mailing list</a> for details"
# [[params.links.developer]]
# 	name = "Developer mailing list"
# 	url = "https://example.org/mail"
# 	icon = "fa fa-envelope"
#         desc = "Discuss development issues around the project"


#### About Author ###
[author]
  name             = "Hari Thapliyaal"
  avatar           = "/assets/images/myphotos/Profilephoto1.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              = "Dr. Hari Thapliyal is a seasoned professional and prolific blogger with a multifaceted background that spans the realms of Data Science, Project Management, and Advait-Vedanta Philosophy. Holding a Doctorate in AI/NLP from SSBM (Geneva, Switzerland), Hari has earned Master's degrees in Computers, Business Management, Data Science, and Economics, reflecting his dedication to continuous learning and a diverse skill set.\n\nWith over three decades of experience in management and leadership, Hari has proven expertise in training, consulting, and coaching within the technology sector. His extensive 16+ years in all phases of software product development are complemented by a decade-long focus on course design, training, coaching, and consulting in Project Management.\n\n In the dynamic field of Data Science, Hari stands out with more than three years of hands-on experience in software development, training course development, training, and mentoring professionals. His areas of specialization include Data Science, AI, Computer Vision, NLP, complex machine learning algorithms, statistical modeling, pattern identification, and extraction of valuable insights.\n\nHari's professional journey showcases his diverse experience in planning and executing multiple types of projects. He excels in driving stakeholders to identify and resolve business problems, consistently delivering excellent results. Beyond the professional sphere, Hari finds solace in long meditation, often seeking secluded places or immersing himself in the embrace of nature."
  short_bio        = "Dr. Hari Thapliyal is a prolific blogger and seasoned professional with an extensive background in Data Science, Project Management, and Advait-Vedanta Philosophy. He holds a Doctorate in AI/NLP from SSBM, Geneva, along with Master’s degrees in Computers, Business Management, Data Science, and Economics. With over three decades of experience in management and leadership, Hari has extensive expertise in training, consulting, and coaching within the technology sector. His specializations include Data Science, AI, Computer Vision, NLP, and machine learning. Hari is also passionate about meditation and nature, often retreating to secluded places for reflection and peace."
  location         = "Bangalore, India."
  email            = "hari@dasarpai.com"

#### Commenting ####
[giscus]
  repo                 = "dasarpai/dasarpai-comments"
  repo_id              = "R_kgDOOGVFpA"  # Shown during giscus setup at https://giscus.app
  category_name        = "General" # Full text name of the category
  category_id          = "DIC_kwDOOGVFpM4CnzHR" # Shown during giscus setup at https://giscus.app
  discussion_term      = "url" # "pathname" (default), "url", "title", "og:title"
  reactions_enabled    = 1 # '1' for enabled (default), '0' for disabled
  theme                = "light" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  strict               = 1 # 1 for enabled, 0 for disabled (default)
  input_position       = "top" # "top", "bottom" # The comment input box will be placed above or below the comments
  emit_metadata        = 1 # 1 for enabled, 0 for disabled (default) # https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#imetadatamessage
  lang                 = "en" # "en" (default)
  lazy                 = true # true, false # Loading of the comments will be deferred until the user scrolls near the comments container.


customCSS = ["css/custom.css"]